import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'release-notes',
    'getting-started',
    {
      type: 'category',
      label: 'Database Setup',
      items: [
        'sqlite-setup',
        'sql-server-setup',
        'postgresql-setup',
        'connection-reference',
      ],
    },
    {
      type: 'category',
      label: 'Usage',
      items: [
        'database-tools',
        'usage-examples',
      ],
    },
    // AI Courses section
    {
      type: 'category',
      label: 'AI Courses',
      items: [
        'ai-courses/AIAgents',
        'ai-courses/GenAICourse',
        'ai-courses/MachineLearning',
      ],
    },
  ],
};

export default sidebars;
